import { config } from 'dotenv';

config({ path: '.env' });

export const {
    PORT,
    DATABASE_URL,
    NODE_ENV,
    JWT_SECRET,
    JWT_EXPIRY,
    JWT_REFRESH_SECRET,
    JWT_REFRESH_EXPIRY,
    EMAIL_USER,
    EMAIL_PASSWORD,
    WEB_URL,
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    GITHUB_CLIENT_ID,
    GITHUB_CLIENT_SECRET,
    MPESA_CONSUMER_KEY,
    MPESA_CONSUMER_SECRET,
    MPESA_PASSKEY,
    MPESA_SHORTCODE,
    MPESA_CALLBACK_URL,
} = process.env;

